# https://nixpacks.com/docs/configuration/file
[variables]
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'

# Python configuration
PYTHONUNBUFFERED = '1'
PYTHONDONTWRITEBYTECODE = '1'
POETRY_VERSION = '1.4.2'      # Optional: specify Poetry version if you're using it
PYTHON_VERSION = '3.11'       # Specify your desired Python version

[phases.setup]
nixPkgs = [
    'python311',                    # Python 3.11
    'python311Packages.pip',
    'python311Packages.setuptools',
    'python311Packages.wheel',
]

[phases.caddy]
dependsOn = ['setup']
nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
nixPkgs = ['caddy']

[phases.install]
dependsOn = ['setup']
cmds = [
    'python -m pip install --upgrade pip',
    # Add your pip install commands here, for example:
    # 'pip install -r requirements.txt'
]

[phases.fmt]
dependsOn = ['caddy']
cmds = ['caddy fmt --overwrite Caddyfile']

[start]
cmd = 'exec caddy run --config Caddyfile --adapter caddyfile 2>&1'
